---
<<<<<<< HEAD
title: Implement tags for an object and search them
=======
title: Create Tags for an Object and Search for Tags
>>>>>>> upstream/master
credit:
  - Gleicon Moraes
tags:
  - tags
  - sets
  - search
  - union
  - diff

